# ---------------------------------------------------------------------------
# IMLAB
# ---------------------------------------------------------------------------

stages:
    - build
    - test
    - cleanup

make:
    stage: build
    script: 
        - mkdir -p build
        - cd build
        - cmake -DCMAKE_BUILD_TYPE=Debug ..
        - make
    cache:
        key: "$CI_COMMIT_REF_NAME"
        paths:
            - build/
        policy: pull-push
    tags:
        - "clang-7"
        - "cmake"
        - "python3"
    artifacts:
        paths:
            - build/tester
        expire_in: 1 hrs

tester:
    stage: test
    script:
        - ./build/tester
    cache:
        key: "$CI_COMMIT_REF_NAME"
        paths:
            - build/
        policy: pull
    tags:
        - "clang-7"
        - "cmake"
        - "python3"
    dependencies:
        - make

cpplint:
    stage: test
    script:
        - mkdir -p build
        - cd build
        - cmake -DCMAKE_BUILD_TYPE=Debug ..
        - make lint
    tags:
        - "clang-7"
        - "cmake"
        - "python3"
